baseURL = "https://mhrosas.github.io/elalfilmatematico/"
defaultContentLanguage = "es"
title = "El alfil matemático" 
theme = "hugo-cards"
paginate = 36

[params]
  author = "El alfil matemático"
  description = "Problemas para todos"
  email="alfilmatematico@gmail.com"

[markup]
  [markup.goldmark]
      [markup.goldmark.renderer]
      unsafe = true
  